# Influenzanet Data Analysis for Country/Platform level

This repository provides data analysis scripts for basic data analysis for one platform/country.

## Requirements

- An R software installation

- Platform's data in a database following the legacy platform's table organization 

## Create the data

### Using ifn-cli 

ifn-cli is command line tool to manage influenzanet platform. The code is available on [github](https://github.com/influenzanet/python-ifncli)

To create the data you need :
- Credentials of an account with at least SERVICE_ACCOUNT permissions

The download of the data has 2 independent steps and commands:
- `response:db:export` : Download the raw data in a file database (this allow download synchronisation) for all the surveys
- `response:db:import` : Import the raw data in an analysis database creating flat table for each survey

## Configure to use you data and your setting

Configuration of the analysis are done with 2 files

- The global configuration : configure the installation (on the machine where the analysis are run)
- The platform file : describe the data of the platform (can be shared across several machines, using the same data) survey structures, ...

### Global Configuration

You need to create a file named `config.R` in config/ directory, this file will contain some variables to tell the analysis how to run the analysis
on the machine where it is installed. It's not under version as it can change on each machine.  

The `DB_DSN` variable has to be set to the path of the analysis db (generated by the `response:db:import` command). It's possible to use 
other database source (like sqlite or PostgreSQL), in this case the DB_DBS has to be a list with `driver` entry to define which database
driver to use (`RSQLite` or `RPostgreSQL`) alongside with other expected parameters to use the `dbConnect()` method of each package (like 'host', 'user', 'password')

`EUROSTAT_COUNTRY` will contain the code of the country, to tell wich population file to use (in data/pop). You can provide your own files
and with another code if they are not provided or you want to customize it.

```R
DB_DSN='/path/to/duckdbfile'
EUROSTAT_COUNTRY='IT' 
```

### Platform configuration

The platform configuration describe the data of the platform in a more permanent way (it can be commited in git to be shared by several machine using the same data)
It defines:
- How survey response data are organized (where to find survey's data in the database, how to recode values...)
- How time is sliced in seasons 

A default definition is provided in 'default_platform.R' and is loaded by default. To customize it, copy this file using another name and set PLATFORM_FILENAME`
variable in 'config/config.R' with the name of the file (without the '.R' extension, e.g. 'my_platform_file' if your file is 'my_platform_file.R')











